datatable_filter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('filter_app.urls', namespace='filter'))
]

filter_app/urls.py
from django.urls import path

from .views import MainView, MainViewFilter


app_name = 'filter'


urlpatterns = [
    path('', MainView.as_view(), name='main_view'),
    path('filter/', MainViewFilter.as_view(), name='main_view_filter')
]

filter_app/models.py
from django.db import models


class Transaction(models.Model):
    amount = models.IntegerField(default=0)
    customer = models.CharField(max_length=255)
    date = models.DateField()
    text = models.TextField()
    another_text = models.CharField(max_length=255)
    boolean_field = models.BooleanField(default=False)
    boolean_field1 = models.BooleanField(default=True)
    boolean_field2 = models.BooleanField(default=True)
    some_text = models.TextField(default='Default text')
    price = models.IntegerField(default=100)
    vendor = models.CharField(max_length=255, default='My vendor')

    @property
    def number_customer(self):
        return f'{self.amount}, {self.customer}'

filter_app/views.py
from django.views.generic import View
from django.shortcuts import render

from .models import Transaction
from filter_datatable.views import DatatableFilterView


class MainView(View):
    template_name = 'index.html'

    def get(self, request):
        return render(request, self.template_name)


class MainViewFilter(DatatableFilterView):
    queryset = Transaction.objects.all()
    columns = ('amount', 'customer', 'date', 'text', 'another_text', 'boolean_field', 'some_text', 'price', 'vendor',
               'boolean_field1', 'boolean_field2', 'number_customer')
    filter_columns = ('amount', )
    filter_range_columns = ['date']
    filter_property = ['number_customer']

filter_datatable/views.py
from django.views.generic import View
from django.http import JsonResponse

from .filter import DatatableFilter


class DatatableFilterView(View):
    """
       Filter view base class that returns filtering data to datatable.

       To use, need to inherit and override next fields:
       columns: all display columns in datatable,
       filter_columns: colums for filtering (default: simple text using searching with icontains)
       filter_range_columns: columns for filtering date in range [from; to]
       actions_fields: fields that will return as dict (F.e. {"id": 1, is_active: true})
           using in specified url generation for every row in datatable
       default_order: field for ordering queryset
       """

    queryset = None
    columns = None
    filter_columns = None
    filter_range_columns = None
    actions_fields = None
    filter_property = None
    default_order = '-pk'

    def get(self, request, *args, **kwargs):
        datatable_filter = DatatableFilter(
            request,
            self.columns,
            self.queryset,
            self.filter_columns,
            self.filter_range_columns,
            self.filter_property,
            self.actions_fields,
            self.default_order
        )
        datatable_filter.run_queries()
        return JsonResponse(datatable_filter.output_result(), safe=False)

    def post(self, request, *args, **kwargs):
        datatable_filter = DatatableFilter(
            request,
            self.columns,
            self.queryset,
            self.filter_columns,
            self.filter_property,
            self.filter_range_columns,
            self.actions_fields,
            self.default_order
        )
        datatable_filter.run_queries()
        return JsonResponse(datatable_filter.output_result(), safe=False)

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Title</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'vendors/css/vendors.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'vendors/css/tables/datatable/dataTables.bootstrap5.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'vendors/css/tables/datatable/responsive.bootstrap5.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'vendors/css/tables/datatable/buttons.bootstrap5.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'vendors/css/tables/datatable/rowGroup.bootstrap5.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'vendors/css/flatpickr/flatpickr.min.css' %}">
</head>
<body>
<div class="container">
	<div class="row">
		<div class="col">
			<input type="text" class="filter-input" id="id_amount" placeholder="Amount">
			<input type="text" class="filter-input" id="id_number_customer" placeholder="Number customer">
			<input type="text" id="id_date" class="form-control flatpickr-range filter-range"
				   placeholder="YYYY-MM-DD to YYYY-MM-DD"/>
			<button type="button" id="filter">Filter</button>
			<button type="button" id="reset">Reset</button>
			<div id="basic-datatable">
				<table class="table table-sm table-bordered" id="datatable">
					<thead>
					<tr>
						<td>Amount</td>
						<td>Customer</td>
						<td>Date</td>
						<td>Text</td>
						<td>Another text</td>
						<td>Boolean Field</td>
						<td>Boolean Field1</td>
						<td>Boolean Field2</td>
						<td>Some text</td>
						<td>Price</td>
						<td>Vendor</td>
						<td>Number/Customer</td>
					</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="{% static 'vendors/js/vendors.min.js' %}"></script>
<script src="{% static 'vendors/js/tables/datatable/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendors/js/tables/datatable/dataTables.bootstrap5.min.js' %}"></script>
<script src="{% static 'vendors/js/tables/datatable/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'vendors/js/tables/datatable/responsive.bootstrap5.min.js' %}"></script>
<script src="{% static 'vendors/js/tables/datatable/datatables.checkboxes.min.js' %}"></script>
<script src="{% static 'vendors/js/tables/datatable/datatables.buttons.min.js' %}"></script>
<script src="{% static 'vendors/js/tables/datatable/buttons.html5.min.js' %}"></script>
<script src="{% static 'vendors/js/tables/datatable/buttons.print.min.js' %}"></script>
<script src="{% static 'vendors/js/tables/datatable/dataTables.rowGroup.min.js' %}"></script>
<script src="{% static 'vendors/js/table-datatables-basic.js' %}"></script>
<script src="{% static 'vendors/js/datatable_filter.js' %}"></script>
<script src="{% static 'vendors/js/flatpickr/flatpickr.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"
		integrity="sha512-qTXRIMyZIFb8iQcfjXWCO8+M5Tbc38Qi5WzdPOYZHIlZpzBHG3L3by84BBBOiRGiEb7KKtAOAs5qYdUiZiQNNQ=="
		crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    const ajax_view = '{% url "filter:main_view_filter" %}';

    const columns = [
        {data: 'amount'},
        {data: 'customer'},
        {data: 'date'},
        {data: 'text'},
        {data: 'another_text'},
        {data: 'boolean_field'},
        {data: 'boolean_field1'},
        {data: 'boolean_field2'},
        {data: 'some_text'},
        {data: 'price'},
        {data: 'vendor'},
        {data: 'number_customer'}
    ]

    function make_flatpickr(){
        let flatpickr = $('#id_date').flatpickr({
            mode: 'range',
            allowInput: true,
            onChange: function(selectedDates){
                dateArr = selectedDates.map(date => moment(date));
            },
            onReady: function(selectedDates){
                dateArr = selectedDates.map(date => moment(date));
            }
        })
        return flatpickr;
    }

    function convert_flatpickr_date(date_input){
        const first_date = date_input.selectedDates[0];
        const second_date = date_input.selectedDates[1];
        const converted_first_date = `${first_date.getFullYear()}-${first_date.getMonth()}-${first_date.getDate()}`;
        const converted_second_date = `${second_date.getFullYear()}-${second_date.getMonth()}-${second_date.getDate()}`;
        if(converted_first_date === converted_second_date){
            return converted_first_date;
		}else{
            return `${converted_first_date} to ${converted_second_date}`;
		}
	}

    $(document).ready(function(){
        const table = make_filtered_datatable($('#datatable'), ajax_view, columns);
        const date_input = make_flatpickr();
        $('#id_date').on('focus', ({ currentTarget }) => $(currentTarget).blur())
        $("#id_date").prop('readonly', false)   // hack to remove readonly parameter without list of previous inputs;

        $('#filter').on('click', function(){
            const amount = $('#id_amount').val();
            const number_customer = $('#id_number_customer').val();
            if(date_input.selectedDates.length){
				const date = convert_flatpickr_date(date_input);
                table.column(2).search(date);
			}
            table.column(0).search(amount);
            table.column(11).search(number_customer);
            table.draw();
        })
        $('#reset').on('click', function(){
            date_input.clear();
            $('#id_amount').val('');
            $('#id_number_customer').val('');
            table.column(0).search('');
            table.column(2).search('');
            table.column(11).search('');
            table.draw();
        })
    })
</script>
</body>
</html>